name: the_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  http:
  shared_preferences: ^2.5.3
  syncfusion_flutter_gauges: ^29.1.41
  fl_chart: ^0.71.0
  google_fonts: ^6.2.1
  jwt_decoder: ^2.0.1
  settings_ui:
  url_launcher: ^6.3.1
  flutter_settings_ui: ^3.0.1
  numberpicker: 
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/pictures/
  - lib/pictures/awards/
  - lib/utils/awards.json
  - lib/utils/

